# Generated by Django 5.0.6 on 2024-06-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
    ]
