# Generated by Django 5.0.6 on 2024-06-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_room_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('can_view_bookings', 'Can view bookings')]},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('can_manage_rooms', 'Can manage rooms')]},
        ),
    ]
