# Generated by Django 5.0.4 on 2024-05-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_doctorappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
