# Generated by Django 5.0.4 on 2024-05-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_branch_alter_studentprofile_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(max_length=100),
        ),
    ]
